from typing import Protocol


class ImageProvider(Protocol):
    def metadata(self) -> dict: ...
    def generate(self, prompt: str) -> bytes: ...


class TextProvider(Protocol):
    def metadata(self) -> dict: ...
    def generate(self, prompt: str) -> str: ...


class PublishingProvider(Protocol):
    def metadata(self) -> dict: ...
    def publish(self, image_path: str | None, caption: str | None) -> dict: ...
